import { readFile, stat } from "node:fs/promises";
import { resolve } from "node:path";

import {
  decisionCatalogSchema,
  type DecisionCatalog,
} from "@ador/shared/decisions";

export function renderDecisionGateReference(input: DecisionCatalog): string {
  const catalog = decisionCatalogSchema.parse(input);
  const lines = [
    "# Decision gates",
    "",
    "Generated from `configs/decision-gates.ts`. Do not edit this file manually.",
    "",
    "## Decisions",
    "",
    "| ID | Status | Owner | Deadline |",
    "|---|---|---|---|",
    ...catalog.decisions.map(
      ({ deadline, id, owner, status }) =>
        `| ${id} | ${status} | ${owner} | ${deadline} |`,
    ),
    "",
    "## Gates",
    "",
    "| Gate | Required accepted decisions |",
    "|---|---|",
    ...catalog.gates.map(
      ({ id, requiredDecisions }) =>
        `| ${id} | ${requiredDecisions.join(", ")} |`,
    ),
    "",
  ];
  return lines.join("\n");
}

function normalizeMarkdownTables(contents: string): string {
  return contents
    .split("\n")
    .map((line) =>
      line.startsWith("|")
        ? `|${line
            .slice(1, -1)
            .split("|")
            .map((cell) => {
              const trimmed = cell.trim();
              return /^-+$/u.test(trimmed) ? "---" : trimmed;
            })
            .join("|")}|`
        : line,
    )
    .join("\n");
}

export async function findDecisionPolicyViolations(
  root: string,
  input: DecisionCatalog,
): Promise<readonly string[]> {
  const catalog = decisionCatalogSchema.parse(input);
  const violations: string[] = [];
  const referencePath = resolve(root, "references/decision-gates.md");
  const expected = renderDecisionGateReference(catalog);
  const actual = await readFile(referencePath, "utf8").catch(() => "");
  if (normalizeMarkdownTables(actual) !== normalizeMarkdownTables(expected)) {
    violations.push(
      "references/decision-gates.md is out of sync with the decision catalog",
    );
  }
  for (const decision of catalog.decisions) {
    if (decision.status !== "accepted") continue;
    const adrIsFile = await stat(resolve(root, decision.adr))
      .then((entry) => entry.isFile())
      .catch(() => false);
    if (!adrIsFile) {
      violations.push(
        `${decision.id} references a missing ADR: ${decision.adr}`,
      );
    }
    for (const evidence of decision.evidence) {
      const evidenceIsFile = await stat(resolve(root, evidence))
        .then((entry) => entry.isFile())
        .catch(() => false);
      if (!evidenceIsFile) {
        violations.push(
          `${decision.id} references missing evidence: ${evidence}`,
        );
      }
    }
  }
  return violations;
}
